### ISSUE TITLE
Neighborhoods not displaying

### ISSUE THREAD

**Issue by tacman** [nyu-mhealth/Recruitment-Interactive#2]
There are no neighborhoods in the dropdown list after installing.

![image](https://cloud.githubusercontent.com/assets/619585/15726730/814b9ec8-2820-11e6-914f-be3e75a5ca60.png)

**Comment by jdgodchaux** [comment]
README now includes:

- Ingest New York City neighborhood list into database by running:
`python manage.py import_nyc_hoods`
